name = "profit-lounge-marketing"
compatibility_date = "2024-02-20"
main = "workers-site/index.js"

[build]
command = "npm run build"
output_dir = "dist"

[site]
bucket = "./dist"

[[routes]]
pattern = "profitlounge.com/*"
zone_id = "your_zone_id"

[[routes]]
pattern = "staging.profitlounge.com/*"
custom_domain = true