name = "profit-lounge-marketing"
compatibility_date = "2024-02-20"

[build]
command = "npm run build"
dist = "dist"

[site]
bucket = "./dist"
entry-point = "workers-site/index.js"

[build.upload]
format = "service-worker"

[[routes]]
pattern = "/*"
script = "workers-site/index.js"

[env.production]
route = "profitlounge.com/*"
zone_id = "your_zone_id"

[env.staging]
route = "staging.profitlounge.com/*"