name = "profit-lounge-marketing"
compatibility_date = "2024-02-20"
main = "dist/index.js"

[site]
bucket = "./dist/public"
include = ["**/*"]

[build]
command = "npm run build"

[compatibility]
nodejs_compat = true

[env.production]
routes = [
  { pattern = "profitlounge.com/*", zone_name = "profitlounge.com" }
]

[env.staging]
routes = [
  { pattern = "staging.profitlounge.com/*", custom_domain = true }
]